@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class GameMainMenu
Class GameMenu
Class EasyMenu
Class DifficultMenu
Class CardMenu
Class "{abstract}\nMenu" as Menu
}

package Game <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Player <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package CodeHunt <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

GameMainMenu ..>  GameMenu
GameMenu ..>   CardMenu
GameMenu ..>  EasyMenu
GameMenu ..> DifficultMenu

GameMenu -[hidden]-|> Menu
EasyMenu -[hidden]-|> Menu
CardMenu -[hidden]-|> Menu
DifficultMenu -[hidden]-|> Menu
GameMainMenu -[hidden]-|> Menu
GameMenu -[hidden]-|> Menu

DifficultMenu -down-> Game
EasyMenu -down-> Game
CodeHunt -down-> GameMainMenu
CardMenu -left-> Player


@enduml