@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class Game LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Package Player <<Rectangle>> MODEL_COLOR{
            Class Card MODEL_COLOR_T2
    }
    Class CodeHunt #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#green]> Game
UI -right[#green]-> Player
Game -down[#blue]-> Player
CodeHunt -up[#grey]-> UI
CodeHunt -right[#grey]-> Storage
CodeHunt -up[#grey]-> Player
CodeHunt -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> Player
Storage .right[STORAGE_COLOR].>File
User ..down> UI
@enduml